#:schema node_modules/wrangler/config-schema.json

account_id = "bb7357f233619f55fc52060622f4eed7"
name = "stripe-customer-verification"
main = "src/index.ts"

compatibility_date = "2025-03-19"
compatibility_flags = ["nodejs_compat"]

[vars]
CORS_ORIGIN = "chrome-extension://eodajmolecppealblndaogcmkjaibfgb"

[env.preview.vars]
CORS_ORIGIN = "chrome-extension://eodajmolecppealblndaogcmkjaibfgb"
name = "stripe-customer-verification-preview"

[observability]
enabled = true
